### ISSUE TITLE
Installation with pip not possible

### ISSUE THREAD

**Issue by turbinenreiter** [south-coast-science/scs_core#96]
Altough there is a `setup.py`, installing with pip is not possible.

`~/SCS/scs_core $ pip3 install . --user`
```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 515, in move_wheel_files
    reader = csv.reader(record_in)
AttributeError: module 'csv' has no attribute 'reader'
```

The reason for this is your custom `csv` module, which name-clashes with the standard library `csv_module`.

**Comment by turbinenreiter** [comment]
Also, following the instructions [here](https://github.com/south-coast-science/scs_documentation/wiki/Installation_Instructions_RaspBerry_Pi_on_Ubuntu-Linux) does not work:

```
Traceback (most recent call last):
  File "./localised_datetime.py", line 29, in <module>
    from scs_core.data.localized_datetime import LocalizedDatetime
ImportError: No module named 'scs_core.data'
```

Altough:
```
pi@host:~/SCS $ ls
scs_analysis  scs_core  scs_dfe_eng  scs_host_rpi  scs_mfr  scs_ndir  scs_osio
```
and:
```
pi@host:~/SCS $ echo $PYTHONPATH  
/home/pi/SCS:/home/pi/SCS/scs_analysis:/home/pi/SCS/scs_analysis/src/scs_analysis:/home/pi/SCS/scs_osio:/home/pi/SCS/scs_osio/src/scs_osio:/home/pi/SCS/scs_host_rpi:/home/pi/SCS/scs_host_rpi/src/scs_host_rpi:/home/pi/SCS/scs_core:/home/pi/SCS/scs_core/src/scs_core:/home/pi/SCS/scs_dfe_eng:/home/pi/SCS/scs_dfe_eng/src/scs_dfe_eng:/home/pi/SCS/scs_mfr:/home/pi/SCS/scs_mfr/src/scs_mfr:/home/pi/SCS/scs_ndir:/home/pi/SCS/scs_ndir/src/scs_ndir:
```

**Comment by turbinenreiter** [comment]
After I manually installed all libraries with `sudo python3 setup.py install` (which fails on half of the libraries), the error messages changes:

```
pi@host:~/SCS/scs_analysis/src/scs_analysis $ ./localised_datetime.py 
Traceback (most recent call last):
  File "./localised_datetime.py", line 31, in <module>
    from scs_analysis.cmd.cmd_localised_datetime import CmdLocalizedDatetime
ImportError: No module named 'scs_analysis.cmd'
```

**Comment by turbinenreiter** [comment]
I'd be happy enough with one, simple, working example on how to use the digital frontend on raspberry pi with the A4 sensors.

**Comment by bruno-beloff** [comment]
Your PYTHONPATH is incorrect. Please see:

https://github.com/south-coast-science/scs_analysis/wiki/1:-Installation

**Comment by bruno-beloff** [comment]
Installation with pip3 is under development. I will look into the csv issue. Thank you for the heads-up.

**Comment by bruno-beloff** [comment]
I appreciate your request for worked examples. We will get there. In the meantime, there is some useful information at:

https://github.com/south-coast-science/docs/wiki/1:-Software-repository-wikis

**Comment by turbinenreiter** [comment]
Thank you very much, that part works now.

I am still lost on actually getting sensor data, tough.

Currently trying to use `gases_sampler.py` from `scs_dev` but:
```
gases_sampler: SystemID not available.
```

I found documentation here: https://github.com/south-coast-science/scs_dev/wiki/gases_sampler and here: https://github.com/south-coast-science/scs_mfr/wiki/2:-Device-configuration

**Comment by turbinenreiter** [comment]
I figured out most of the configuration, except the `SystemID` - I just removed the lines then.

Now I am stuck at this:
`./gases_sampler.py`

```
Traceback (most recent call last):
  File "./gases.py", line 148, in <module>
    afe = None if dfe_conf is None else dfe_conf.afe(Host)
  File "/home/pi/SCS/scs_dfe_eng/src/scs_dfe/board/dfe_conf.py", line 103, in afe
    return AFE(self, pt1000, sensors)
  File "/home/pi/SCS/scs_dfe_eng/src/scs_dfe/gas/afe.py", line 49, in __init__
    self.__wrk_adc = ADS1115(ADS1115.ADDR_WRK, AFE.__RATE)
  File "/home/pi/SCS/scs_dfe_eng/src/scs_dfe/gas/ads1115.py", line 144, in __init__
    self.__write_config(self.__config)
  File "/home/pi/SCS/scs_dfe_eng/src/scs_dfe/gas/ads1115.py", line 225, in __write_config
    I2C.write(ADS1115.__REG_CONFIG, config >> 8, config & 0xff)
  File "/home/pi/SCS/scs_host_rpi/src/scs_host/bus/i2c.py", line 108, in write
    I2C.__FW.write(bytearray(values))
OSError: [Errno 121] Remote I/O error
```

which to me looks like the I2C device isn't there?

**Comment by bruno-beloff** [comment]
The system ID feature was included to make it possible to confirm which device was publishing on which message topic. You experience shows me that - for people who are not using messaging - an absent system ID should be ignored, and no tag included in the output. I will implement this change.

In the meantime, you can enter whatever you want! The only restriction, I think, is that the serial number should be an integer.

**Comment by turbinenreiter** [comment]
I understand. I thought a wrong configuration cause my following issue:

When I try to run `gases_sampler.py` with this configuration, I'm stuck
at this error message:
```
$ ~/SCS/scs_dev/src/scs_dev/gases_sampler.py
Traceback (most recent call last):
  File "/home/pi/SCS/scs_dev/src/scs_dev/gases_sampler.py", line 160,
in <module>
    afe = None if dfe_conf is None else dfe_conf.afe(Host)
  File "/home/pi/SCS/scs_dfe_eng/src/scs_dfe/board/dfe_conf.py", line
103, in afe
    return AFE(self, pt1000, sensors)
  File "/home/pi/SCS/scs_dfe_eng/src/scs_dfe/gas/afe.py", line 49, in
__init__
    self.__wrk_adc = ADS1115(ADS1115.ADDR_WRK, AFE.__RATE)
  File "/home/pi/SCS/scs_dfe_eng/src/scs_dfe/gas/ads1115.py", line 144,
in __init__
    self.__write_config(self.__config)
  File "/home/pi/SCS/scs_dfe_eng/src/scs_dfe/gas/ads1115.py", line 225,
in __write_config
    I2C.write(ADS1115.__REG_CONFIG, config >> 8, config & 0xff)
  File "/home/pi/SCS/scs_host_rpi/src/scs_host/bus/i2c.py", line 108,
in write
    I2C.__FW.write(bytearray(values))
OSError: [Errno 121] Remote I/O error
```

To me, that looks like an I2C communication error, so I checked which
I2C devices are connected:

```
$ sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 1f
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- 44 -- -- -- 48 49 -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- 68 -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --    
```

**Comment by bruno-beloff** [comment]
The DFE has two ADS1115 ADCs. Their I2C addresses are 0x48 and 0x49 - so the detect looks OK.

Please check the I2C bus: does the following work?

~/SCS/scs_dev/src/scs_dev/climate_sampler.py

(the SHT31 board must be attached).
